Hw1
jabooticaba/java_automation pull request #1
Opened 2021-08-27 08:51 UTC by jabooticaba

2021-09-01 17:46 UTC, Teraule requested changes

2021-09-01 17:46 UTC, Teraule commented on hw1/src/main/java/model/Kotik.java
> +    System.out.println("Скушал " + x + " кусочков еды");
где то потерялась табуляция

2021-09-01 17:46 UTC, Teraule commented on hw1/src/main/java/model/Kotik.java
> +    public void liveAnotherDay() {  //Не придумал, как сократить конструкцию!
котик в процессе деятельности не голодает. то есть я могу взять и отдельно вызывать методы действия бесконечно. у нас есть метод eat, который делает кота более сытым, пусть тогда метод действия делает котика более голодным.

2021-09-01 17:46 UTC, Teraule commented on hw1/src/main/java/model/Kotik.java
> +    public void liveAnotherDay() {  //Не придумал, как сократить конструкцию!
Если котику нужно будет поесть в процесса работы метода, то метод выведет больше чем 24 строки

2021-09-02 05:26 UTC, jabooticaba commented on hw1/src/main/java/model/Kotik.java
> +    System.out.println("Скушал " + x + " кусочков еды");
исправлено

2021-09-02 05:31 UTC, jabooticaba commented on hw1/src/main/java/model/Kotik.java
> +    public void liveAnotherDay() {  //Не придумал, как сократить конструкцию!
Механизм голодания добавил.

> Если котику нужно будет поесть в процесса работы метода, то метод выведет больше чем 24 строки
Сделал так, чтобы не больше 24 строк было.  Если нужен другой способ, уточните, пожалуйста.

2021-09-06 13:47 UTC, merged