Hw3
jabooticaba/java_automation pull request #3
Opened 2021-09-05 12:17 UTC by jabooticaba

2021-09-06 15:09 UTC, jabooticaba commented
Логи прикручу по мере возможности, услышал ваши пожелания)

2021-09-14 13:39 UTC, Teraule requested changes

2021-09-14 13:39 UTC, Teraule commented on hw3/src/main/java/animals/Worker.java
> +    }
просто просто параметр типа Voice, зачем лишняя связь с типом животного

2021-09-14 13:39 UTC, Teraule commented on hw3/src/main/java/custom/Size.java
> +    XLARGE (4);
тоже норм, но данный конкретный случай вышел вырожденным, так как у енума есть ordinal, который возвращает порядок элемента в енуме и без value работало бы точно так же

2021-09-14 13:39 UTC, Teraule commented on hw3/src/main/java/animals/Carnivorus.java
> +        try {
предлагаю ловить исключение не внутри eat, а где-нибудь там, где мы его пытаемся покормить

2021-11-24 09:57 UTC, merged